#!/bin/bash
#
# tomcat       Starts Tomcat Java server.
#
#
# chkconfig: 345 88 12
# description: Tomcat is the server for 
# Java servlet applications.
### BEGIN INIT INFO
# Provides: $tomcat
### END INIT INFO

JAVA_HOME=/etc/alternatives/java_sdk
export JAVA_HOME
TOMCAT_HOME=/opt/tomcat-sakai/bin
START_TOMCAT=$TOMCAT_HOME/startup.sh

# Source function library.
. /etc/init.d/functions

[ -f $START_TOMCAT ] || exit 0

RETVAL=0

umask 077

# Make sure we don't get hit by 'Too many open files'
ulimit -Hn 16384
ulimit -Sn 4096

start() {
        echo -n $"Starting Tomcat server: "
        daemon su -c $START_TOMCAT vagrant
        echo
        return $RETVAL
}
stop() {
        echo -n $"Shutting down Tomcat server: "
        kill `jps | grep Bootstrap | cut -f1 -d' '` > /dev/null 2>&1
        echo
        return $RETVAL
}
restart() {
        stop
        start
}
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?